[package]
name = "importer-settings"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
importer-domain = { path = "../importer-domain" }
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]

[lints]
workspace = true
